<?php
/**
 * @var Klevu\Metadata\Block\MetadataInterface $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$klevuPageMeta = $block->getKlevuPageMeta();
?>
<?php if ($klevuPageMeta): ?>
    <!--suppress ES6ConvertVarToLetConst -->
    <?php
    $scriptString = <<<script

        var klevu_page_meta = {$klevuPageMeta};

script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript', 'id' => 'klevu_page_meta'],
        $scriptString,
        false
    ) ?>
<?php endif; ?>
